version: "3.8"
services:
  bot:
    build: .
    restart: always
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./volume/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: pheme
      MONGO_INITDB_ROOT_PASSWORD: pheme
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: pheme
      ME_CONFIG_MONGODB_ADMINPASSWORD: pheme
